version: '3.9'
services:
   
  apache:
    build: ./Apache_d/.
    tty: true
    networks:
      challenge:
        ipv4_address:  172.16.88.33
    ports:
     - "2000:80"
     - "2001:22"
  
  webssh:
    build: ./ubuntu1/.
    networks:
      challenge:
        ipv4_address: 172.16.88.11
    ports:
     - "8080:80"
     - "3333:22"   

  ftp:
    build: ./ubuntu2/.
    networks:
      challenge:
        ipv4_address: 172.16.88.19    

networks:
  challenge:
    ipam:
      driver: default
      config:
        - subnet: 172.16.88.0/24
